routes/web.php
<?php

use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PostController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware'=>'auth'],function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::view('dashboard','dashboard')->name('dashboard');

    Route::group(['prefix'=>'change-password'], function () {
        Route::view('/','auth.passwords.change')->name('change_password');
        Route::put('/',[ProfileController::class,'changePassword'])->name('change');
    });

    Route::group(['prefix'=>'profile', 'as'=>'profile.'], function () {
        Route::view('/','profile.index')->name('index');
        Route::get('/edit',[ProfileController::class,'index'])->name('edit');
        Route::post('/',[ProfileController::class,'store'])->name('store');
        Route::get('/avatar',[ProfileController::class,'removeAvatar'])->name('avatar.remove');

    });

    Route::group(['prefix'=>'posts', 'as'=>'post.'], function () {
        Route::get('/', [PostController::class,'index'])->name('index');
        Route::get('/create', [PostController::class,'create'])->name('create');
        Route::post('/store', [PostController::class,'store'])->name('store');

        Route::group(['prefix'=>'{post}'] ,function () {
            Route::get('/edit', [PostController::class,'edit'])->name('edit');
            Route::put('/', [PostController::class,'update'])->name('update');
            Route::get('/', [PostController::class,'show'])->name('show');
            Route::delete('/', [PostController::class,'destroy'])->name('destroy');
        });
    });

    Route::group(['middleware'=>'is_adult', 'prefix'=>'comments', 'as'=>'comment.'], function () {
        Route::post('/store', [CommentController::class, 'store'])->name('store');
        Route::post('/reply/store', [CommentController::class, 'replyStore'])->name('reply.add');

        Route::group(['prefix'=>'{comment}'], function () {
            Route::get('/edit', [CommentController::class, 'edit'])->name('edit');
            Route::put('/', [CommentController::class, 'update'])->name('update');
            Route::delete('/', [CommentController::class, 'destroy'])->name('delete');
        });

    });

    Route::group(['prefix'=>'notifications', 'as'=>'notifications.'], function () {
        Route::get('/', [NotificationController::class,'index'])->name('index');
        Route::get('/{notification}', [NotificationController::class,'markAsRead'])->name('read.mark');
        Route::delete('/{notification}', [NotificationController::class,'destroy'])->name('delete');
    });

    Route::get('/follow/{post}',[FollowerController::class,'follow'])->name('follow');
    Route::get('/un-follow/{post}',[FollowerController::class,'unFollow'])->name('unfollow');

});

Route::fallback(function () {
    return view('home');
});















//
Route::get('test',function () {
    $users = \App\Models\Post::find(19)->comments;
    $users = \App\Models\Comment::all();
    dd($users);

});

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Dashboard') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <h2>Hello, {{Auth::user()->name}}</h2>
                        <p>Current Logged in at - <strong>{{Auth::user()->current_logged_in->diffForHumans()}}</strong></p>
                        <p>Last Logged in at - <strong>{{Auth::user()->last_logged_in->diffForHumans()}}</strong></p>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Home Page') }}</div>
                @if (session('change'))
                    <div class="alert alert-success" role="alert">
                        {{ session('change') }}
                    </div>
                @endif
                <div class="card-body">

                    <h1>This is Homepage</h1>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/notifications.blade.php
@extends('layouts.app')

@section('content')
<div style="text-align: center">
{{--<h3>These are notifications</h3>--}}
<br>

<ul>
@forelse ($unreadNotifications as $notification)
     <li class="alert alert-success" role="alert">{{$notification->data['creator']}}({{$notification->created_at->diffForHumans()}}) ->
         <a href="{{$notification->data['baseUrl']}}" style="color: #e74c3c">go to post</a>
         <a href="{{route('notifications.read.mark',$notification->id)}}" style="color: #2980b9; margin-left: 50px">Mark as read</a>
         <form action="{{route('notifications.delete',$notification->id)}}" method="post" class="d-inline ml-5">
             @csrf
             @method('delete')
             <button type="submit" class="btn btn-outline-danger">Delete</button>
         </form>
     </li>
@empty
    <h3 style="color: #218838">No unread notifications for you!</h3>
@endforelse
</ul>
<hr style="background: #7f8c8d; height: 10px; margin: 50px"/>
{{--<h3>Already Read notification</h3>--}}
<ul>
@forelse ($notifications as $notification)
     <li class="alert alert-danger" role="alert">{{$notification->data['creator']}} ({{$notification->created_at->diffForHumans()}}) ->
         <a href="{{$notification->data['baseUrl']}}" style="color: red">go to post</a>
         <form action="{{route('notifications.delete',$notification->id)}}" method="post" class="d-inline ml-5">
             @csrf
             @method('delete')
             <button type="submit" class="btn btn-outline-danger">Delete</button>
         </form>
     </li>
@empty
    <h5 style="color: #c0392b">No already read notifications for you!</h5>
@endforelse
</ul>
</div>
@endsection