routes/web.php
<?php

use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PostController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware'=>'auth'],function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::view('dashboard','dashboard')->name('dashboard');

    Route::group(['prefix'=>'change-password'], function () {
        Route::view('/','auth.passwords.change')->name('change_password');
        Route::put('/',[ProfileController::class,'changePassword'])->name('change');
    });

    Route::group(['prefix'=>'profile', 'as'=>'profile.'], function () {
        Route::view('/','profile.index')->name('index');
        Route::get('/edit',[ProfileController::class,'index'])->name('edit');
        Route::post('/',[ProfileController::class,'store'])->name('store');
        Route::get('/avatar',[ProfileController::class,'removeAvatar'])->name('avatar.remove');

    });

    Route::group(['prefix'=>'posts', 'as'=>'post.'], function () {
        Route::get('/', [PostController::class,'index'])->name('index');
        Route::get('/create', [PostController::class,'create'])->name('create');
        Route::post('/store', [PostController::class,'store'])->name('store');

        Route::group(['prefix'=>'{post}'] ,function () {
            Route::get('/edit', [PostController::class,'edit'])->name('edit');
            Route::put('/', [PostController::class,'update'])->name('update');
            Route::get('/', [PostController::class,'show'])->name('show');
            Route::delete('/', [PostController::class,'destroy'])->name('destroy');
        });
    });

    Route::group(['middleware'=>'is_adult', 'prefix'=>'comments', 'as'=>'comment.'], function () {
        Route::post('/store', [CommentController::class, 'store'])->name('store');
        Route::post('/reply/store', [CommentController::class, 'replyStore'])->name('reply.add');

        Route::group(['prefix'=>'{comment}'], function () {
            Route::get('/edit', [CommentController::class, 'edit'])->name('edit');
            Route::put('/', [CommentController::class, 'update'])->name('update');
            Route::delete('/', [CommentController::class, 'destroy'])->name('delete');
        });

    });

    Route::group(['prefix'=>'notifications', 'as'=>'notifications.'], function () {
        Route::get('/', [NotificationController::class,'index'])->name('index');
        Route::get('/{notification}', [NotificationController::class,'markAsRead'])->name('read.mark');
        Route::delete('/{notification}', [NotificationController::class,'destroy'])->name('delete');
    });

    Route::get('/follow/{post}',[FollowerController::class,'follow'])->name('follow');
    Route::get('/un-follow/{post}',[FollowerController::class,'unFollow'])->name('unfollow');

});

Route::fallback(function () {
    return view('home');
});















//
Route::get('test',function () {
    $users = \App\Models\Post::find(19)->comments;
    $users = \App\Models\Comment::all();
    dd($users);

});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable')->whereNull('parent_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'post_tag')->using(PostTag::class);
    }

    protected $casts = [
        'images'=>'array'
    ];

    public function getTitleAttribute($value)
    {
        return strtoupper($value);
    }


//    protected $attributes = [
//        'is_adult' => '0',
//    ];

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{

    public function index(Request $request)
    {

        $query = Post::query();
        if (request('term')) {
            $query->where('title', 'Like', '%' . request('term') . '%')
                    ->orwhereHas('tags', function ($q) use ($request) {
                            $q->where('tags.tag','Like', request('term') );
                    });
        }

        $posts = $query->latest()->with('tags')->withCount('comments')->paginate(5);
        return view('posts.index', compact('posts'));
    }

    public function create()
    {
        $tags = Tag::all();
        return view('posts.create',compact('tags'));
    }

    public function store(Request $request) {
//        dd($request['tags']);
        $request->validate([
            'title' => 'required|unique:posts|max:255',
            'description' => 'required',
            'tags'=>'required',
            'images'=>'max:2',
            'images.*' => 'image|mimes:jpeg,png,jpg,gif,webp,svg|max:2048',
        ]);
        $post =  new Post;

        if ($request->hasfile('images')) {
            $images = $request->file('images');
            $img = [];
            foreach($images as $image) {
                $name = time().'.'.$image->getClientOriginalName();
                $image->storeAs('public/images/posts', $name);
                $img[] = $name;
            }
            $post->images = $img;
        }

        $post->title = $request['title'];
        $post->user_id = Auth::user()->id;
        $post->description = $request['description'];

        $post->is_adult = $request->boolean('is_adult');
        $post->save();

        $tags = $request['tags'];
        $tagIds = [];
        foreach($tags as $tagName)
        {
            $tag = Tag::firstOrCreate(['tag'=>$tagName]);
            if($tag)
            {
                $tagIds[] = $tag->id;
            }
        }
        $post->tags()->sync($tagIds);

        return redirect('posts')->with(['success'=>'Post is created successfully!']);
    }

    public function show(Post $post)
    {

        return view('posts.show', compact('post'));
    }

    public function edit(Post $post) {

        $this->authorize('update', $post);

        $tags = Tag::all();
        return view('posts.edit', compact(['post','tags']));
    }

    public function update(Request $request, Post $post) {

        $this->authorize('update', $post);

        $request->validate([
            'title' => 'required|max:255|unique:posts,title,'.$post->id,
            'description' => 'required',
            'images'=>'max:2',
            'images.*' => 'image|mimes:jpeg,png,jpg,gif,webp,svg|max:2048',
        ]);
//        if (!$request['is_adult']) {
//            $request['is_adult'] = 0;
//        }
        if ($request->hasfile('images')) {

            if ($post->images) {
                foreach($post->images as $image){
                    Storage::delete('public/images/posts/'.$image);
                }
            }
            $images = $request->file('images');
            $img = [];
            foreach($images as $image) {
                $name = time().'.'.$image->getClientOriginalName();
                $image->storeAs('public/images/posts', $name);
                $img[] = $name;
            }
            $post->images = $img;
        }
        $post->title = $request['title'];
        $post->user_id = Auth::user()->id;
        $post->description = $request['description'];
        $post->is_adult = $request->boolean('is_adult');


        $post->save();

        $tags = $request['tags'];
        $tagIds = [];
        foreach($tags as $tagName)
        {

            $tag = Tag::firstOrCreate(['tag'=>$tagName]);
            if($tag)
            {
                $tagIds[] = $tag->id;
            }

        }
        $post->tags()->sync($tagIds);

        return redirect('posts')->with(['success'=>'Post is Updated successfully!']);
    }

    public function destroy(Post $post) {
        $this->authorize('delete', $post);

        if ($post->images) {
            foreach ($post->images as $image) {
                Storage::delete('public/images/posts/' . $image);
            }
        }
        if ($comments = $post->comments) {
            foreach($comments as $comment) {
                $comment->delete();
            }
        }
        $post->delete();
        return redirect('posts')->with(['success'=>'Post is deleted successfully!']);
    }
}

app/Http/Controllers/api/PostController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Http\Resources\PostCollection;
use App\Models\Post;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    public function index(Request $request)
    {
        return new PostCollection(Post::all());
    }

    public function create()
    {
        $tags = Tag::all();
        return view('posts.create',compact('tags'));
    }

    public function store(Request $request) {
//        dd($request['tags']);
        $request->validate([
            'title' => 'required|unique:posts|max:255',
            'description' => 'required',
            'tags'=>'required',
        ]);
        $post =  new Post;

        if ($request->hasfile('images')) {
            $images = $request->file('images');
            $img = [];
            foreach($images as $image) {
                $name = time().'.'.$image->getClientOriginalName();
                $image->storeAs('public/images/posts', $name);
                $img[] = $name;
            }
            $post->images = $img;
        }

        $post->title = $request['title'];
        $post->user_id = Auth::user()->id;
        $post->description = $request['description'];

        $post->is_adult = $request->boolean('is_adult');
        $post->save();

        $tags = $request['tags'];
        $tagIds = [];
        foreach($tags as $tagName)
        {
            $tag = Tag::firstOrCreate(['tag'=>$tagName]);
            if($tag)
            {
                $tagIds[] = $tag->id;
            }
        }
        $post->tags()->sync($tagIds);

        return redirect('posts')->with(['success'=>'Post is created successfully!']);
    }

    public function show(Post $post)
    {

        return view('posts.show', compact('post'));
    }

    public function edit(Post $post) {

        $this->authorize('update', $post);

        $tags = Tag::all();
        return view('posts.edit', compact(['post','tags']));
    }

    public function update(Request $request, Post $post) {

        $this->authorize('update', $post);

        $request->validate([
            'title' => 'required|max:255|unique:posts,title,'.$post->id,
            'description' => 'required',
            'images'=>'max:2',
            'images.*' => 'image|mimes:jpeg,png,jpg,gif,webp,svg|max:2048',
        ]);
//        if (!$request['is_adult']) {
//            $request['is_adult'] = 0;
//        }
        if ($request->hasfile('images')) {

            if ($post->images) {
                foreach($post->images as $image){
                    Storage::delete('public/images/posts/'.$image);
                }
            }
            $images = $request->file('images');
            $img = [];
            foreach($images as $image) {
                $name = time().'.'.$image->getClientOriginalName();
                $image->storeAs('public/images/posts', $name);
                $img[] = $name;
            }
            $post->images = $img;
        }
        $post->title = $request['title'];
        $post->user_id = Auth::user()->id;
        $post->description = $request['description'];
        $post->is_adult = $request->boolean('is_adult');


        $post->save();

        $tags = $request['tags'];
        $tagIds = [];
        foreach($tags as $tagName)
        {

            $tag = Tag::firstOrCreate(['tag'=>$tagName]);
            if($tag)
            {
                $tagIds[] = $tag->id;
            }

        }
        $post->tags()->sync($tagIds);

        return redirect('posts')->with(['success'=>'Post is Updated successfully!']);
    }

    public function destroy(Post $post) {
        $this->authorize('delete', $post);

        if ($post->images) {
            foreach ($post->images as $image) {
                Storage::delete('public/images/posts/' . $image);
            }
        }
        if ($comments = $post->comments) {
            foreach($comments as $comment) {
                $comment->delete();
            }
        }
        $post->delete();
        return redirect('posts')->with(['success'=>'Post is deleted successfully!']);
    }
}

resources/views/posts/comment_replies.blade.php
@foreach($comments as $comment)
    <div class="display-comment" class="d-inline-flex">
        @if (Auth::user()->avatar)
            <img src="{{asset('storage/images/'.Auth::user()->avatar)}}"
                 height="30px" width="30px" style="border-radius: 50%">
        @else
            <img src="{{asset('storage/images/user.png')}}"
                 height="30px" width="30px" style="border-radius: 50%">
        @endif
        <strong>{{ $comment->user->name }}</strong>
        <p>{{ $comment->body }} <span style="float: right"><i class="fa fa-calendar"></i>{{$comment->created_at->diffForHumans()}}</span></p>


        <div style="display: flex">
            <form method="post" action="{{ route('comment.reply.add') }}" >
                @csrf
                <div class="form-group">
                    <input type="text" name="comment_body" class="form-control" />
                    <input type="hidden" name="post_id" value="{{ $post_id }}" />
                    <input type="hidden" name="comment_id" value="{{ $comment->id }}" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-info"><i class="fa fa-reply"></i></button>
                </div>
            </form>
            @can('update', $comment)
                    <a>
                        <button class="btn btn-outline-success editBtn" data-toggle="modal" data-target="#exampleModal"
                            data-body="{{$comment->body}}" data-id="{{$comment->id}}" >
                        <i class="fa fa-edit"></i>
                        </button>
                    </a>
            @endcan
            @can('delete', $comment)
                    <form action="{{route('comment.delete',$comment->id)}}" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-outline-danger"><i class="fa fa-trash"></i></button>
                    </form>
            @endcan
        </div>
        @include('posts.comment_replies', ['comments' => $comment->replies])
    </div>
@endforeach


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modify Your Comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ route('comment.update','comment') }}">
{{--                    @csrf--}}
                    {!! csrf_field() !!}
                    @method('put')
                    <div class="form-group row">
                        <label for="comment" class="col-md-4 col-form-label text-md-right">{{ __('Change Comment') }}</label>

                        <div class="col-md-6">
                            <input id="comment" type="text" class="form-control" name="body" >
                            <input id="comment_id" type="hidden" class="form-control" name="comment_id" >
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Change comment') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <h2 class="d-inline">Create Post</h2>
                        <a href="{{route('post.index')}}" class="btn btn-outline-primary float-right"><i class="fa fa-chevron-left" ></i></a>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('post.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label class="label" for="title">Post Title: </label>
                                <input type="text" name="title" id="title" class="form-control" required/>
                            </div>
                            <div class="form-group">
                                <label class="label" for="body">Post Description: </label>
                                <textarea name="description" id="body" rows="10" cols="30" class="form-control" required></textarea>
                            </div>
                            <div class="form-group">
                                <label class="label" for="tags">Tags </label>
                                <select name="tags[]" id="tags" class="form-select form-control tags @error('tags') is-invalid @enderror" multiple>
                                    @foreach($tags as $tag)
                                        <option value="{{$tag->tag}}">
                                            {{$tag->tag}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="label" for="images">Upload Images: </label>
                                <input type="file" name="images[]" id="images" class="form-control-file" multiple/>
                            </div>
                            <div class="form-check form-group">
                                <input class="form-check-input" type="checkbox" name="is_adult" value="1" id="adult">
                                <label class="form-check-label" for="adult">
                                    18+ Content
                                </label>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-success" value="Create" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
{{--@section('scripts')--}}
{{--    <script>--}}
{{--        $(document).ready(function() {--}}
{{--            $(function () {--}}
{{--                $("input[type = 'submit']").on('click',function (e) {--}}
{{--                    let $fileUpload = $("input[type='file']");--}}
{{--                    // console.log(parseInt($fileUpload.get(0).files.length));--}}
{{--                    if (parseInt($fileUpload.get(0).files.length) > 2) {--}}
{{--                        alert("You are only allowed to upload a maximum of 3 files");--}}
{{--                        e.preventDefault();--}}
{{--                    }--}}
{{--                });--}}
{{--            });--}}
{{--        });--}}
{{--    </script>--}}
{{--@endsection--}}

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <h2 class="d-inline">Edit Post</h2>
                        <a href="{{route('post.index')}}" class="btn btn-outline-primary float-right"><i class="fa fa-chevron-left" ></i></a></div>
                    <div class="card-body">
                        <form method="post" action="{{ route('post.update',$post->id) }}" enctype="multipart/form-data">
                            <div class="form-group">
                                @csrf
                                @method('put')
                                <label class="label" for="title">Post Title: </label>
                                <input type="text" name="title" id="title" class="form-control" value="{{$post->title}}"/>
                            </div>
                            <div class="form-group">
                                <label class="label" for="body">Post Description: </label>
                                <textarea name="description" id="body" rows="10" cols="30" class="form-control" required>{{$post->description}}</textarea>
                            </div>
                            <div class="form-group">
                                <label class="label" for="tags">Tags </label>
                                <select name="tags[]" id="tags" class="form-select form-control tags @error('tags') is-invalid @enderror" multiple>
                                    @foreach($tags as $tag)
                                        <option value="{{$tag->tag}}" @if (in_array($tag->tag,$post->tags->pluck('tag')->all()))
                                                selected
                                                @endif >
                                            {{$tag->tag}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                @if ($post->images)
                                    @foreach($post->images as $image)
                                        <img src="{{asset('storage/images/posts/'.$image)}}" alt="featured" width="100px">
                                    @endforeach
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="label" for="images">Change Images: </label>
                                <input type="file" name="images[]" id="images" class="form-control-file" multiple/>
                            </div>
                            <div class="form-check form-group">
                                <input class="form-check-input" type="checkbox" name="is_adult" value="1" id="adult"
                                        @if ($post->is_adult == 1)
                                            checked
                                        @endif>
                                <label class="form-check-label" for="adult">
                                    18+ Content
                                </label>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-success" value="Update" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
{{--@section('scripts')--}}
{{--    <script>--}}
{{--        $(document).ready(function() {--}}
{{--            $(function () {--}}
{{--                $("input[type = 'submit']").on('click',function (e) {--}}
{{--                    let $fileUpload = $("input[type='file']");--}}
{{--                    // console.log(parseInt($fileUpload.get(0).files.length));--}}
{{--                    if (parseInt($fileUpload.get(0).files.length) > 2) {--}}
{{--                        alert("You are only allowed to upload a maximum of 3 files");--}}
{{--                        e.preventDefault();--}}
{{--                    }--}}
{{--                });--}}
{{--            });--}}
{{--        });--}}
{{--    </script>--}}
{{--@endsection--}}

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if($msg = Session::get('success'))
                    <div class="alert alert-success">
                        {{$msg}}
                    </div>
                @endif
                    <div class="mx-auto pull-left">
                            <form action="{{ route('post.index') }}" method="GET" role="search">
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <a href="{{ route('post.index') }}">
                                         <span class="input-group-btn">
                                             <button class="btn btn-outline-danger" type="button" title="Refresh page">
                                                 <span class="fa fa-refresh"></span>
                                             </button>
                                        </span>
                                    </a>
                                     </span>
                                    <input type="text" class="form-control" name="term" placeholder="Search posts" id="term">
                                    <button class="btn btn-outline-info" type="submit" title="Search posts">
                                        <span class="fa fa-search"></span>
                                    </button>
                                </div>
                            </form>
                        </div>
                <div class="float-right mb-3">
                    <a href="{{route('post.create')}}" class="btn btn-success"><i class="fa fa-plus-circle" ></i></a>
                </div>
                <table class="table table-striped mt-3">
                    <thead>
                    <th>Title</th>
                    <th class="actions"> Action</th>
                    </thead>
                    <tbody>
                    @forelse($posts as $post)
                        <tr>
                            <td class="description"><h3><strong  @if ($post->is_adult == 1)
                                             class="badge badge-danger"
                                             @endif class="badge badge-secondary">{{ $post->title }}</strong>
                                </h3>
                                <p>Author : {{$post->user->name}}</p>
                                <p>Created_at : {{$post->created_at->diffForHumans()}}</p>
                                <p>Comments : {{$post->comments_count}}</p>
                                @foreach($post->tags as $tag)
                                    <h5 class="d-inline"><span class="badge badge-success">{{ $tag->tag }}</span></h5>
                                @endforeach
                            </td>
                            <td class="actions">

                                <form action="{{route('post.destroy', $post->id)}}"  method="post">
                                    @csrf
                                    <a href="{{route('post.show',  $post->id)}}" class="btn btn-outline-success"><i class="fa fa-eye"></i></a>
                                    @can('update', $post)
                                         <a href="{{route('post.edit',  $post->id)}}" class="btn btn-outline-primary"><i class="fa fa-edit"></i></a>
                                    @endcan
                                    @method('delete')
                                    @can('update', $post)
                                        <button type="submit" class="btn btn-outline-danger"><i class="fa fa-trash"></i></button>
                                    @endcan
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td><h3>No post found!</h3></td>
                        </tr>
                    @endforelse
                    </tbody>

                </table>
                    {{ $posts->links() }}
            </div>
        </div>
    </div>
@endsection

@section('css')
p{
line-height: 10px;
}
table {
width: 100%;
table-layout: fixed;
}

.actions {
max-width:10%;
text-align: right;
padding-right:4px;
}

.description {
text-overflow: ellipsis;
white-space: nowrap;
overflow: hidden;
width:80%;
max-width:80%;
}
@endsection