routes/web.php
<?php

use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PostController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware'=>'auth'],function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::view('dashboard','dashboard')->name('dashboard');

    Route::group(['prefix'=>'change-password'], function () {
        Route::view('/','auth.passwords.change')->name('change_password');
        Route::put('/',[ProfileController::class,'changePassword'])->name('change');
    });

    Route::group(['prefix'=>'profile', 'as'=>'profile.'], function () {
        Route::view('/','profile.index')->name('index');
        Route::get('/edit',[ProfileController::class,'index'])->name('edit');
        Route::post('/',[ProfileController::class,'store'])->name('store');
        Route::get('/avatar',[ProfileController::class,'removeAvatar'])->name('avatar.remove');

    });

    Route::group(['prefix'=>'posts', 'as'=>'post.'], function () {
        Route::get('/', [PostController::class,'index'])->name('index');
        Route::get('/create', [PostController::class,'create'])->name('create');
        Route::post('/store', [PostController::class,'store'])->name('store');

        Route::group(['prefix'=>'{post}'] ,function () {
            Route::get('/edit', [PostController::class,'edit'])->name('edit');
            Route::put('/', [PostController::class,'update'])->name('update');
            Route::get('/', [PostController::class,'show'])->name('show');
            Route::delete('/', [PostController::class,'destroy'])->name('destroy');
        });
    });

    Route::group(['middleware'=>'is_adult', 'prefix'=>'comments', 'as'=>'comment.'], function () {
        Route::post('/store', [CommentController::class, 'store'])->name('store');
        Route::post('/reply/store', [CommentController::class, 'replyStore'])->name('reply.add');

        Route::group(['prefix'=>'{comment}'], function () {
            Route::get('/edit', [CommentController::class, 'edit'])->name('edit');
            Route::put('/', [CommentController::class, 'update'])->name('update');
            Route::delete('/', [CommentController::class, 'destroy'])->name('delete');
        });

    });

    Route::group(['prefix'=>'notifications', 'as'=>'notifications.'], function () {
        Route::get('/', [NotificationController::class,'index'])->name('index');
        Route::get('/{notification}', [NotificationController::class,'markAsRead'])->name('read.mark');
        Route::delete('/{notification}', [NotificationController::class,'destroy'])->name('delete');
    });

    Route::get('/follow/{post}',[FollowerController::class,'follow'])->name('follow');
    Route::get('/un-follow/{post}',[FollowerController::class,'unFollow'])->name('unfollow');

});

Route::fallback(function () {
    return view('home');
});















//
Route::get('test',function () {
    $users = \App\Models\Post::find(19)->comments;
    $users = \App\Models\Comment::all();
    dd($users);

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css">
{{--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>--}}
{{--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>--}}

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <style>
        .display-comment .display-comment {
            margin-left: 40px
        }
        @yield('css')
    </style>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    <img src="{{asset('storage/images/laravel.png')}}"
                         height="30px" width="30px" >
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                        <li class="nav-item mr-auto">
                            <a class="nav-link" href="{{route('dashboard')}}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('post.index')}}">Blog</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" href="{{route('notifications.index')}}">
                                 Notifications
                                <span class="badge badge-dark">{{Auth::user()->notifications()->count()}}</span>
                            </a>
                         </li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                    @if (Auth::user()->avatar)
                                        <img src="{{asset('storage/images/'.Auth::user()->avatar)}}"
                                             height="30px" width="30px" style="border-radius: 50%">
                                    @else
                                    <img src="{{asset('storage/images/user.png')}}"
                                         height="30px" width="30px" style="border-radius: 50%">
                                    @endif
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('profile.index') }}">
                                        {{ __('Profile') }}
                                    </a>
                                    <a class="dropdown-item" href="{{route('change_password')}}">
                                        {{ __('Change Password') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

{{--    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>--}}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>



    <script>
    $(document).ready(function() {
         $.noConflict();
         $('.languages').select2({
                placeholder : "Select multiple languages",
                allowclear : true,
          });
         $('.interests').select2({
                placeholder : "Select multiple Tags",
                allowclear : true,
          });
    });

    $(".tags").select2({
        placeholder : "Select or Add tags",
        tags: true,
        tokenSeparators: [',', ' ']
    })
    </script>

    @yield('scripts')
</body>
</html>